# Generated by Django 5.2.10 on 2026-01-07 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], default='INDIVIDUAL', max_length=10)),
                ('evaluable', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('CALIFICADA', 'Calificada')], default='PENDIENTE', max_length=10)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='tareas_participa', to='tareas.alumno')),
                ('creador_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to='tareas.alumno')),
                ('creador_profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to='tareas.profesor')),
                ('profesor_evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_evaluadas', to='tareas.profesor')),
            ],
        ),
    ]
